spring.application.name=backendBioLense

spring.profiles.active=dev

spring.jpa.open-in-view=false

plant.id.api.key=G1Re1ZScOrr1OHj8ToMqW8zGrR13JFyJOy2n2eKaeJKCPjPKc7

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB