# ── Datasource
spring.datasource.url=jdbc:h2:file:./biolense-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# ── JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ── H2 Console enables in develpoment
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# ── Spring Security default user (dev only)
spring.security.user.name=admin
spring.security.user.password=admin