# ── Datasource
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/biolense
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ── JPA

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# ── H2 Console (disabled in production)
spring.h2.console.enabled=false